components/.vitepress/config.ts
components/spinner/component.md
components/truncate/Truncate.spec.ts
components/truncate/Truncate.vue
components/truncate/component.md

feat(truncate): add component truncate

---

components/avatar/component.md

fix avatar doc

---

src/.vitepress/config.ts
src/components/collapse/Collapse.spec.ts
src/components/collapse/Collapse.vue
src/components/collapse/index.md
src/components/nav/NavItem.vue
src/components/tabs/Tabs.vue

added: add collapse component

---

.github/workflows/ci.yml
package.json
packages/browserslist-config/package.json
packages/eslint-config-persona/package.json
packages/persona-icon/package.json
packages/persona/package.json
packages/tailwind-animation/package.json
packages/tailwind-extended/package.json
packages/tailwind-preset/package.json
src/components/modal/Modal.vue
src/icons/collections.md
yarn.lock

--------------
We add new our icon pack under package `@privyid/persona-icon`
- **text**:
- Add transform and weight prop, update documentation, create unit test - by **Afiq Yasin Ramadhan** [<samp>(18d3f)</samp>](https://github.com/privy-open-source/design-system/commit/18d3fd53efa)
- **others**: reorganizing order of component layer, add z-index docs in variables-foundation - by **Afiq Yasin Ramadhan** [<samp>(20d80)</samp>](https://github.com/privy-open-source/design-system/commit/20d80c44e33)
- **navbar**: centering items inside navbar-nav, add menu-class in the dropdown and nav-item-dropdown - by **Afiq Yasin Ramadhan** [<samp>(37d3f)</samp>](https://github.com/privy-open-source/design-system/commit/37d3fc76d8c)
- **button**: Centering button text, remove text decoration line on …

release: `0.13.0`

---

packages/persona/src/module.ts
src/components/calendar/adapter/adapter.ts
src/components/pdf-object/test.md
src/styleguide/navigation/index.md

fix(calendar): fix error import

---

package.json
packages/browserslist-config/package.json
packages/eslint-config-persona/package.json
packages/persona-icon/package.json
packages/persona/package.json
packages/persona/src/module.ts
packages/tailwind-animation/package.json
packages/tailwind-extended/package.json
packages/tailwind-preset/package.json
src/components/dropdown/Dropdown.vue
src/components/modal/index.md
src/components/select/Select.vue
yarn.lock

hotfix: cannot find date-fns on build prod

---

src/components/tabs/index.md

- update docs for set default tab active in tabs component

Docs: update documentation for tabs

---

src/components/table/index.md

Hi maintainer,
Here I add docs in table about props in table props fields

docs: add field props in table props api

---

src/components/card/Card.vue
src/components/card/index.md
src/components/sidebar-menu/index.ts
src/components/toggle/Toggle.vue

List variables
```
--p-card-padding-x: theme(spacing.6);
--p-card-padding-y: theme(spacing.6);
--p-card-bg: theme(backgroundColor.default.DEFAULT);
--p-card-bg-dark: theme(backgroundColor.dark.default.DEFAULT);
--p-card-border: theme(borderColor.default.DEFAULT);
--p-card-border-dark: theme(borderColor.default.DEFAULT);
--p-card-color: theme(textColor.default);
--p-card-color-dark: theme(textColor.dark.default);
```

feat(card): add custom variables for card

---

src/components/dropdown/DropdownItem.spec.ts
src/components/dropdown/DropdownItem.vue
src/components/dropdown/index.md
src/components/select/Select.vue
src/components/select/index.md
src/components/select/index.ts

Hi creator,
I hope you're well! I've created this pull request to add a new feature to the Select component that allows disabling individual items.
**Changes:**
- Added disabled property in an options object to handle disabled item
**Motivation:**
The purpose of this update is to give users more control over the Select component by allowing them to disable specific items. This feature enhances user experience and ensures that certain options cannot be selected when needed.
**Testing:**
I've performed thorough testing to ensure the new functionality works as expected:
Unit tests for the new disabled prop.
- make sure that the disabled item have disabled property in their element
Notes:
I've updated the codebase documentation and comments to reflect the changes accurately.
Please review …

[Pull Request] Adding Ability to Disable Item in Select Component

---

src/components/sidebar-menu/SidebarMenu.spec.ts
src/components/sidebar-menu/SidebarMenu.vue
src/components/sidebar-menu/index.spec.ts
src/components/sidebar-menu/index.ts
src/components/sidebar/SidebarNav.vue
src/core/index.ts

This PR add util `filterMenu` in `@privyid/persona/core` for filtering Sidebar Menu

feat(sidebar-menu): add utils `filterMenu`

---

src/components/card/Card.vue

feat(card): change card rounded

---

src/components/dropdown/Dropdown.vue
src/components/dropdown/index.md
src/components/dropdown/index.ts

Provide new size of dropdown with extra large dropdown-menu-container for background process and notification case. Dropdown container have 36rem witdth

feat(dropdown): new sizing of dropdown (xl)

---

package.json
packages/persona/src/module.ts
src/.vitepress/theme/components/Home.vue
src/components/pdf-viewer/__mocks__/use-window-size.ts
src/components/pdf-viewer/utils/use-sticky.spec.ts
src/components/pdf-viewer/utils/use-sticky.ts
src/ecosystem/index.md
yarn.lock

This PR fixed issue on layout mode fixed, viewer height not reactive when window resized

fix(pdf-viewer): fix viewer height when window resized on layout fixed

---

src/components/table-static/TableStatic.spec.ts
src/components/table-static/TableStatic.vue
src/components/table/Table.spec.ts
src/components/table/Table.vue

Select all checkbox on selectable table should be unchecked if there's empty items

fix(table): unchecked select all on table static if no items

---

src/components/toast/Toast.spec.ts
src/components/toast/Toast.vue
src/components/toast/ToastContainer.spec.ts
src/components/toast/ToastContainer.vue
src/components/toast/index.md
src/components/toast/index.ts

toast text isn't mandatory
support markdown for toast text and title
custom icon for toast

feat(toast): support markdown and custom icon

---

src/.vitepress/config.ts
src/components/input-color/index.md
src/components/input-color/index.ts
src/components/input-color/input-color.spec.ts
src/components/input-color/inputColor.vue

- input color components
- documentation of input color
- unit testing

feat(input-color): input color components

---

src/components/navbar/Navbar.vue
src/components/navbar/index.md
src/components/sidebar/Sidebar.vue
src/components/sidebar/SidebarContent.vue
src/components/sidebar/index.md

Create variables of sidebar and navbar for enhance realtime customization. 
Hope can solve the broken layout issue before all css loaded.

feat: add variables in sidebar and navbar for realtime customization

---

packages/tailwind-preset/index.js
src/components/banner/Banner.vue
src/components/banner/index.md
src/components/banner/index.ts
src/components/dropdown/index.md
src/components/input/index.md
src/components/progress-indicator/ProgressIndicator.vue
src/components/progress/Progress.vue
src/components/progressbar/Progressbar.vue
src/components/spinner/SpinnerRing.spec.ts
src/components/spinner/SpinnerRing.vue
src/components/spinner/SpinnerRinggo.spec.ts
src/components/spinner/SpinnerRinggo.vue
src/foundation/colors/Colors.json

Change foundation color.
Change component's color:
1. Progress
2. Progressbar
3. Progress indicator

fix: change color and update components

---

src/components/button/Button.vue
src/components/navbar/Navbar.vue

1. refine button variant variable
2. provide custum global navbar variable

fix: refine button variant variable

---

src/components/datepicker/Datepicker.vue
src/components/datepicker/index.md

The datepicker placement can be customize based on dropdown placement.
[Dropdown placement align](https://privy-open-source.github.io/design-system/components/dropdown/#placement-align)

feat: create placement for datepicker

---

src/components/button/Button.vue
src/components/button/index.md
src/components/card/Card.spec.ts
src/components/card/Card.vue
src/components/card/index.md
src/components/card/index.ts

Refine card style and adjust spacing variant of card. 
Source:

refine card

---

src/components/card/Card.spec.ts
src/components/card/Card.vue
src/components/card/CardSection.spec.ts
src/components/card/CardSection.vue
src/components/card/index.md

- Refine disabled card state
- make readonly state

Card: refine card state
